version: '3'

services:
  #  gateway-service:
  gateway-service:
    image: rhsalska55/gateway-service
    build:
      context: ./gateway-service
      args:
        MAVEN_PROFILE: alpha
    container_name: gateway-service
    ports:
      - "8100:8100"
    environment:
      - SPRING_PROFILES_ACTIVE=alpha

#  user-service
  user-service:
    image: rhsalska55/user-service
    build:
      context: ./user-service
      args:
        MAVEN_PROFILE: alpha
    container_name: user-service
    depends_on:
      - gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=alpha

#  catalog-service
  catalog-service:
    image: rhsalska55/catalog-service
    build:
      context: ./catalog-service
      args:
        MAVEN_PROFILE: alpha
    container_name: catalog-service
    depends_on:
      - gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=alpha


#  order-service
  order-service:
    image: rhsalska55/order-service
    build:
      context: ./order-service
      args:
        MAVEN_PROFILE: alpha
    container_name: order-service
    depends_on:
      - gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=alpha
