apiVersion: v1
kind: Service
metadata:
  name: service-discovery-service
spec:
  type: NodePort
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000