version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    restart: on-failure

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    restart: on-failure

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: on-failure

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../support/dockerscript/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: on-failure

  mysql:
    build: ../../support/dockerscript/mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
#      - ../supportsub/mysqlmount:/var/lib/mysql #namedvolume으로 대체
      - mysql-data:/var/lib/
    ports:
      - 3306:3306
    restart: on-failure

#  service-discovery: >> 도커 컴포즈 / 스웜으로 대체
#    image: rhsalska55/service-discovery
#    build:
#      context: ./service-discovery
#      args:
#        MAVEN_PROFILE: alpha
#    container_name: service-discovery
#    ports:
#      - "8000:8000"
#    environment:
#      - SPRING_PROFILES_ACTIVE=alpha
#    restart: on-failure

  config-service:
    image: rhsalska55/config-service
    build:
      context: ../../config-service
      args:
        MAVEN_PROFILE: alpha
    container_name: config-service
    ports:
      - "8888:8888"
    volumes:
      - ../configurations:/configurations
    environment:
      - SPRING_PROFILES_ACTIVE=alpha
    restart: on-failure

volumes: #named volume 드라이버 옵션 (local, cloud) 등 옵션을 설정할 수 있음
  mysql-data: