server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: '{cipher}abc7c43bc0213d35bd2012a80ccef8d5377c6dc70da4ba14fc3dd84b1a348b4c'
    password: '{cipher}abc7c43bc0213d35bd2012a80ccef8d5377c6dc70da4ba14fc3dd84b1a348b4c'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
  kafka:
    consumer:
      group-id: consumer-group-id