server:
  port: 0
  # 0지정하면 무작위 내장 톰캣 포트가 지정된다. 다만 유래카에서는 어떤 포트를 할당 받더라도 0번 포트만 보이게된다. eureka-instance-id값을 등록하여 관리도 가능하다.
  # -Dserver.port vm옵션을 통해 포트풀을 지정하여 실행 가능.
  # 서비스 디스커버리에 등록되어 있기 때문에 무작위로 포트가 생성되어도 트래킹이 가능하고 lb를 통하여 올바른 요청을 보낼 수 있다.

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: '{cipher}abc7c43bc0213d35bd2012a80ccef8d5377c6dc70da4ba14fc3dd84b1a348b4c'
    password: '{cipher}abc7c43bc0213d35bd2012a80ccef8d5377c6dc70da4ba14fc3dd84b1a348b4c'
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  gateway:
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/user-service/**

order_service:
  #  url: http://127.0.0.1:8000/order-service/%s/orders
  url: http://order-service/%s/orders
  exception:
    orders_is_empty: order is empty